/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SupplierPaymentsRouteImport } from './routes/supplier-payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrintStationRouteImport } from './routes/print-station'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PurchasesIndexRouteImport } from './routes/purchases.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as ReportsStockRouteImport } from './routes/reports.stock'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsProfitabilityRouteImport } from './routes/reports.profitability'
import { Route as ReportsCollectionsRouteImport } from './routes/reports.collections'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as PurchasesIdRouteImport } from './routes/purchases.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as SuppliersIdStatementRouteImport } from './routes/suppliers.$id.statement'
import { Route as ReturnsSalesNewRouteImport } from './routes/returns.sales.new'
import { Route as ReturnsSalesIdRouteImport } from './routes/returns.sales.$id'
import { Route as ReturnsPurchaseNewRouteImport } from './routes/returns.purchase.new'
import { Route as ReturnsPurchaseIdRouteImport } from './routes/returns.purchase.$id'
import { Route as PurchasesIdEditRouteImport } from './routes/purchases.$id.edit'
import { Route as ProductsIdHistoryRouteImport } from './routes/products.$id.history'
import { Route as InvoicesIdEditRouteImport } from './routes/invoices.$id.edit'
import { Route as CustomersIdStatementRouteImport } from './routes/customers.$id.statement'
import { Route as ApiSmsSendRouteImport } from './routes/api/sms.send'
import { Route as ApiSmsCheckRouteImport } from './routes/api/sms.check'
import { Route as ReturnsSalesIdEditRouteImport } from './routes/returns.sales.$id.edit'
import { Route as ReturnsPurchaseIdEditRouteImport } from './routes/returns.purchase.$id.edit'
import { Route as ApiPublicWindowsDownloadFileRouteImport } from './routes/api/public/windows-download.$file'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPaymentsRoute = SupplierPaymentsRouteImport.update({
  id: '/supplier-payments',
  path: '/supplier-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintStationRoute = PrintStationRouteImport.update({
  id: '/print-station',
  path: '/print-station',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReturnsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const PurchasesIndexRoute = PurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStockRoute = ReportsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProfitabilityRoute = ReportsProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCollectionsRoute = ReportsCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => ReportsRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: '/purchases/$id',
  path: '/purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdStatementRoute = SuppliersIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => SuppliersIdRoute,
} as any)
const ReturnsSalesNewRoute = ReturnsSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => ReturnsRoute,
} as any)
const ReturnsSalesIdRoute = ReturnsSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => ReturnsRoute,
} as any)
const ReturnsPurchaseNewRoute = ReturnsPurchaseNewRouteImport.update({
  id: '/purchase/new',
  path: '/purchase/new',
  getParentRoute: () => ReturnsRoute,
} as any)
const ReturnsPurchaseIdRoute = ReturnsPurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => ReturnsRoute,
} as any)
const PurchasesIdEditRoute = PurchasesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PurchasesIdRoute,
} as any)
const ProductsIdHistoryRoute = ProductsIdHistoryRouteImport.update({
  id: '/products/$id/history',
  path: '/products/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesIdRoute,
} as any)
const CustomersIdStatementRoute = CustomersIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => CustomersIdRoute,
} as any)
const ApiSmsSendRoute = ApiSmsSendRouteImport.update({
  id: '/api/sms/send',
  path: '/api/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsCheckRoute = ApiSmsCheckRouteImport.update({
  id: '/api/sms/check',
  path: '/api/sms/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsSalesIdEditRoute = ReturnsSalesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ReturnsSalesIdRoute,
} as any)
const ReturnsPurchaseIdEditRoute = ReturnsPurchaseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ReturnsPurchaseIdRoute,
} as any)
const ApiPublicWindowsDownloadFileRoute =
  ApiPublicWindowsDownloadFileRouteImport.update({
    id: '/api/public/windows-download/$file',
    path: '/api/public/windows-download/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/print-station': typeof PrintStationRoute
  '/reports': typeof ReportsRouteWithChildren
  '/returns': typeof ReturnsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/users': typeof UsersRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/profitability': typeof ReportsProfitabilityRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/sms/check': typeof ApiSmsCheckRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/products/$id/history': typeof ProductsIdHistoryRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/returns/purchase/$id': typeof ReturnsPurchaseIdRouteWithChildren
  '/returns/purchase/new': typeof ReturnsPurchaseNewRoute
  '/returns/sales/$id': typeof ReturnsSalesIdRouteWithChildren
  '/returns/sales/new': typeof ReturnsSalesNewRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
  '/api/public/windows-download/$file': typeof ApiPublicWindowsDownloadFileRoute
  '/returns/purchase/$id/edit': typeof ReturnsPurchaseIdEditRoute
  '/returns/sales/$id/edit': typeof ReturnsSalesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/print-station': typeof PrintStationRoute
  '/settings': typeof SettingsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/users': typeof UsersRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/profitability': typeof ReportsProfitabilityRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/api/sms/check': typeof ApiSmsCheckRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/products/$id/history': typeof ProductsIdHistoryRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/returns/purchase/$id': typeof ReturnsPurchaseIdRouteWithChildren
  '/returns/purchase/new': typeof ReturnsPurchaseNewRoute
  '/returns/sales/$id': typeof ReturnsSalesIdRouteWithChildren
  '/returns/sales/new': typeof ReturnsSalesNewRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
  '/api/public/windows-download/$file': typeof ApiPublicWindowsDownloadFileRoute
  '/returns/purchase/$id/edit': typeof ReturnsPurchaseIdEditRoute
  '/returns/sales/$id/edit': typeof ReturnsSalesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/payments': typeof PaymentsRoute
  '/pos': typeof PosRoute
  '/print-station': typeof PrintStationRoute
  '/reports': typeof ReportsRouteWithChildren
  '/returns': typeof ReturnsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/users': typeof UsersRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/purchases/$id': typeof PurchasesIdRouteWithChildren
  '/purchases/new': typeof PurchasesNewRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/profitability': typeof ReportsProfitabilityRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/suppliers/$id': typeof SuppliersIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/sms/check': typeof ApiSmsCheckRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/customers/$id/statement': typeof CustomersIdStatementRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/products/$id/history': typeof ProductsIdHistoryRoute
  '/purchases/$id/edit': typeof PurchasesIdEditRoute
  '/returns/purchase/$id': typeof ReturnsPurchaseIdRouteWithChildren
  '/returns/purchase/new': typeof ReturnsPurchaseNewRoute
  '/returns/sales/$id': typeof ReturnsSalesIdRouteWithChildren
  '/returns/sales/new': typeof ReturnsSalesNewRoute
  '/suppliers/$id/statement': typeof SuppliersIdStatementRoute
  '/api/public/windows-download/$file': typeof ApiPublicWindowsDownloadFileRoute
  '/returns/purchase/$id/edit': typeof ReturnsPurchaseIdEditRoute
  '/returns/sales/$id/edit': typeof ReturnsSalesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/payments'
    | '/pos'
    | '/print-station'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/supplier-payments'
    | '/users'
    | '/customers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/reports/collections'
    | '/reports/profitability'
    | '/reports/sales'
    | '/reports/stock'
    | '/suppliers/$id'
    | '/customers/'
    | '/invoices/'
    | '/products/'
    | '/purchases/'
    | '/reports/'
    | '/returns/'
    | '/suppliers/'
    | '/api/sms/check'
    | '/api/sms/send'
    | '/customers/$id/statement'
    | '/invoices/$id/edit'
    | '/products/$id/history'
    | '/purchases/$id/edit'
    | '/returns/purchase/$id'
    | '/returns/purchase/new'
    | '/returns/sales/$id'
    | '/returns/sales/new'
    | '/suppliers/$id/statement'
    | '/api/public/windows-download/$file'
    | '/returns/purchase/$id/edit'
    | '/returns/sales/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/payments'
    | '/pos'
    | '/print-station'
    | '/settings'
    | '/supplier-payments'
    | '/users'
    | '/customers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/reports/collections'
    | '/reports/profitability'
    | '/reports/sales'
    | '/reports/stock'
    | '/suppliers/$id'
    | '/customers'
    | '/invoices'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/returns'
    | '/suppliers'
    | '/api/sms/check'
    | '/api/sms/send'
    | '/customers/$id/statement'
    | '/invoices/$id/edit'
    | '/products/$id/history'
    | '/purchases/$id/edit'
    | '/returns/purchase/$id'
    | '/returns/purchase/new'
    | '/returns/sales/$id'
    | '/returns/sales/new'
    | '/suppliers/$id/statement'
    | '/api/public/windows-download/$file'
    | '/returns/purchase/$id/edit'
    | '/returns/sales/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/payments'
    | '/pos'
    | '/print-station'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/supplier-payments'
    | '/users'
    | '/customers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/purchases/$id'
    | '/purchases/new'
    | '/reports/collections'
    | '/reports/profitability'
    | '/reports/sales'
    | '/reports/stock'
    | '/suppliers/$id'
    | '/customers/'
    | '/invoices/'
    | '/products/'
    | '/purchases/'
    | '/reports/'
    | '/returns/'
    | '/suppliers/'
    | '/api/sms/check'
    | '/api/sms/send'
    | '/customers/$id/statement'
    | '/invoices/$id/edit'
    | '/products/$id/history'
    | '/purchases/$id/edit'
    | '/returns/purchase/$id'
    | '/returns/purchase/new'
    | '/returns/sales/$id'
    | '/returns/sales/new'
    | '/suppliers/$id/statement'
    | '/api/public/windows-download/$file'
    | '/returns/purchase/$id/edit'
    | '/returns/sales/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  PaymentsRoute: typeof PaymentsRoute
  PosRoute: typeof PosRoute
  PrintStationRoute: typeof PrintStationRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ReturnsRoute: typeof ReturnsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SupplierPaymentsRoute: typeof SupplierPaymentsRoute
  UsersRoute: typeof UsersRoute
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  InvoicesIdRoute: typeof InvoicesIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  PurchasesIdRoute: typeof PurchasesIdRouteWithChildren
  PurchasesNewRoute: typeof PurchasesNewRoute
  SuppliersIdRoute: typeof SuppliersIdRouteWithChildren
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  ApiSmsCheckRoute: typeof ApiSmsCheckRoute
  ApiSmsSendRoute: typeof ApiSmsSendRoute
  ProductsIdHistoryRoute: typeof ProductsIdHistoryRoute
  ApiPublicWindowsDownloadFileRoute: typeof ApiPublicWindowsDownloadFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-payments': {
      id: '/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/supplier-payments'
      preLoaderRoute: typeof SupplierPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-station': {
      id: '/print-station'
      path: '/print-station'
      fullPath: '/print-station'
      preLoaderRoute: typeof PrintStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof ReturnsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof PurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/stock': {
      id: '/reports/stock'
      path: '/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof ReportsStockRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/profitability': {
      id: '/reports/profitability'
      path: '/profitability'
      fullPath: '/reports/profitability'
      preLoaderRoute: typeof ReportsProfitabilityRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/collections': {
      id: '/reports/collections'
      path: '/collections'
      fullPath: '/reports/collections'
      preLoaderRoute: typeof ReportsCollectionsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/$id': {
      id: '/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id/statement': {
      id: '/suppliers/$id/statement'
      path: '/statement'
      fullPath: '/suppliers/$id/statement'
      preLoaderRoute: typeof SuppliersIdStatementRouteImport
      parentRoute: typeof SuppliersIdRoute
    }
    '/returns/sales/new': {
      id: '/returns/sales/new'
      path: '/sales/new'
      fullPath: '/returns/sales/new'
      preLoaderRoute: typeof ReturnsSalesNewRouteImport
      parentRoute: typeof ReturnsRoute
    }
    '/returns/sales/$id': {
      id: '/returns/sales/$id'
      path: '/sales/$id'
      fullPath: '/returns/sales/$id'
      preLoaderRoute: typeof ReturnsSalesIdRouteImport
      parentRoute: typeof ReturnsRoute
    }
    '/returns/purchase/new': {
      id: '/returns/purchase/new'
      path: '/purchase/new'
      fullPath: '/returns/purchase/new'
      preLoaderRoute: typeof ReturnsPurchaseNewRouteImport
      parentRoute: typeof ReturnsRoute
    }
    '/returns/purchase/$id': {
      id: '/returns/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/returns/purchase/$id'
      preLoaderRoute: typeof ReturnsPurchaseIdRouteImport
      parentRoute: typeof ReturnsRoute
    }
    '/purchases/$id/edit': {
      id: '/purchases/$id/edit'
      path: '/edit'
      fullPath: '/purchases/$id/edit'
      preLoaderRoute: typeof PurchasesIdEditRouteImport
      parentRoute: typeof PurchasesIdRoute
    }
    '/products/$id/history': {
      id: '/products/$id/history'
      path: '/products/$id/history'
      fullPath: '/products/$id/history'
      preLoaderRoute: typeof ProductsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id/edit': {
      id: '/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
    '/customers/$id/statement': {
      id: '/customers/$id/statement'
      path: '/statement'
      fullPath: '/customers/$id/statement'
      preLoaderRoute: typeof CustomersIdStatementRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/api/sms/send': {
      id: '/api/sms/send'
      path: '/api/sms/send'
      fullPath: '/api/sms/send'
      preLoaderRoute: typeof ApiSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/check': {
      id: '/api/sms/check'
      path: '/api/sms/check'
      fullPath: '/api/sms/check'
      preLoaderRoute: typeof ApiSmsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/sales/$id/edit': {
      id: '/returns/sales/$id/edit'
      path: '/edit'
      fullPath: '/returns/sales/$id/edit'
      preLoaderRoute: typeof ReturnsSalesIdEditRouteImport
      parentRoute: typeof ReturnsSalesIdRoute
    }
    '/returns/purchase/$id/edit': {
      id: '/returns/purchase/$id/edit'
      path: '/edit'
      fullPath: '/returns/purchase/$id/edit'
      preLoaderRoute: typeof ReturnsPurchaseIdEditRouteImport
      parentRoute: typeof ReturnsPurchaseIdRoute
    }
    '/api/public/windows-download/$file': {
      id: '/api/public/windows-download/$file'
      path: '/api/public/windows-download/$file'
      fullPath: '/api/public/windows-download/$file'
      preLoaderRoute: typeof ApiPublicWindowsDownloadFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsCollectionsRoute: typeof ReportsCollectionsRoute
  ReportsProfitabilityRoute: typeof ReportsProfitabilityRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsStockRoute: typeof ReportsStockRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCollectionsRoute: ReportsCollectionsRoute,
  ReportsProfitabilityRoute: ReportsProfitabilityRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsStockRoute: ReportsStockRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ReturnsPurchaseIdRouteChildren {
  ReturnsPurchaseIdEditRoute: typeof ReturnsPurchaseIdEditRoute
}

const ReturnsPurchaseIdRouteChildren: ReturnsPurchaseIdRouteChildren = {
  ReturnsPurchaseIdEditRoute: ReturnsPurchaseIdEditRoute,
}

const ReturnsPurchaseIdRouteWithChildren =
  ReturnsPurchaseIdRoute._addFileChildren(ReturnsPurchaseIdRouteChildren)

interface ReturnsSalesIdRouteChildren {
  ReturnsSalesIdEditRoute: typeof ReturnsSalesIdEditRoute
}

const ReturnsSalesIdRouteChildren: ReturnsSalesIdRouteChildren = {
  ReturnsSalesIdEditRoute: ReturnsSalesIdEditRoute,
}

const ReturnsSalesIdRouteWithChildren = ReturnsSalesIdRoute._addFileChildren(
  ReturnsSalesIdRouteChildren,
)

interface ReturnsRouteChildren {
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  ReturnsPurchaseIdRoute: typeof ReturnsPurchaseIdRouteWithChildren
  ReturnsPurchaseNewRoute: typeof ReturnsPurchaseNewRoute
  ReturnsSalesIdRoute: typeof ReturnsSalesIdRouteWithChildren
  ReturnsSalesNewRoute: typeof ReturnsSalesNewRoute
}

const ReturnsRouteChildren: ReturnsRouteChildren = {
  ReturnsIndexRoute: ReturnsIndexRoute,
  ReturnsPurchaseIdRoute: ReturnsPurchaseIdRouteWithChildren,
  ReturnsPurchaseNewRoute: ReturnsPurchaseNewRoute,
  ReturnsSalesIdRoute: ReturnsSalesIdRouteWithChildren,
  ReturnsSalesNewRoute: ReturnsSalesNewRoute,
}

const ReturnsRouteWithChildren =
  ReturnsRoute._addFileChildren(ReturnsRouteChildren)

interface CustomersIdRouteChildren {
  CustomersIdStatementRoute: typeof CustomersIdStatementRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdStatementRoute: CustomersIdStatementRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface InvoicesIdRouteChildren {
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
}

const InvoicesIdRouteChildren: InvoicesIdRouteChildren = {
  InvoicesIdEditRoute: InvoicesIdEditRoute,
}

const InvoicesIdRouteWithChildren = InvoicesIdRoute._addFileChildren(
  InvoicesIdRouteChildren,
)

interface PurchasesIdRouteChildren {
  PurchasesIdEditRoute: typeof PurchasesIdEditRoute
}

const PurchasesIdRouteChildren: PurchasesIdRouteChildren = {
  PurchasesIdEditRoute: PurchasesIdEditRoute,
}

const PurchasesIdRouteWithChildren = PurchasesIdRoute._addFileChildren(
  PurchasesIdRouteChildren,
)

interface SuppliersIdRouteChildren {
  SuppliersIdStatementRoute: typeof SuppliersIdStatementRoute
}

const SuppliersIdRouteChildren: SuppliersIdRouteChildren = {
  SuppliersIdStatementRoute: SuppliersIdStatementRoute,
}

const SuppliersIdRouteWithChildren = SuppliersIdRoute._addFileChildren(
  SuppliersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  PaymentsRoute: PaymentsRoute,
  PosRoute: PosRoute,
  PrintStationRoute: PrintStationRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ReturnsRoute: ReturnsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SupplierPaymentsRoute: SupplierPaymentsRoute,
  UsersRoute: UsersRoute,
  CustomersIdRoute: CustomersIdRouteWithChildren,
  InvoicesIdRoute: InvoicesIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  PurchasesIdRoute: PurchasesIdRouteWithChildren,
  PurchasesNewRoute: PurchasesNewRoute,
  SuppliersIdRoute: SuppliersIdRouteWithChildren,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  ApiSmsCheckRoute: ApiSmsCheckRoute,
  ApiSmsSendRoute: ApiSmsSendRoute,
  ProductsIdHistoryRoute: ProductsIdHistoryRoute,
  ApiPublicWindowsDownloadFileRoute: ApiPublicWindowsDownloadFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
